site_name: Linear Models for Astronomers
nav:
    - Introduction: 0-1_introduction.ipynb
    - Writing Down Linear Models: 1-1_writing-down-linear-models.ipynb
    - Fitting Linear Models: 1-2_fitting-linear-models.ipynb
    - Real Life Linear Models: 1-3_real-life-linear-models.ipynb
    - High Dimensional Real Life Linear Models: 1-4-real-life-linear-models-ND.ipynb
    - Advanced Real Life Linear Models: 1-5_real-life-linear-models-advanced.ipynb
    - Adding Noise: 2-1_adding_noise.ipynb
    - Making Periodograms: 3-1_classical-periodograms.ipynb
    
theme:
  name: "material"
  icon:
    logo: material/chart-timeline-variant-shimmer
  palette:
    scheme: default
    primary: blue grey
    accent: black
repo_url: https://github.com/christinahedges/BuildingFastLinearModels
plugins:
  - search
  - mkdocs-jupyter:
      execute: False
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg